// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using UrGuide.Data;

namespace UrGuide.Data.Migrations
{
    [DbContext(typeof(UrGuideContext))]
    [Migration("20200618120106_Cascade_Delete_On_Sub_Entities")]
    partial class Cascade_Delete_On_Sub_Entities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UrGuide.Data.Entities.Messages.Notification", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MessageId")
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasError")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("Sent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id")
                        .HasName("PK_Messages");

                    b.ToTable("Notifications","ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Posts.Category", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CategoryId")
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("CategoryName")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id")
                        .HasName("PK_Post_Categories");

                    b.ToTable("Post_Categories","ug");

                    b.HasData(
                        new
                        {
                            Id = "d1442a22-adc5-4eab-a232-6ae1fe1ad4f5",
                            Archived = false,
                            Created = new DateTime(2020, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageLink = "images/sport.png",
                            LastUpdated = new DateTime(2020, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sport"
                        },
                        new
                        {
                            Id = "62cf86ff-755d-46fd-bf8d-ca08ba353451",
                            Archived = false,
                            Created = new DateTime(2020, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageLink = "images/nature.png",
                            LastUpdated = new DateTime(2020, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nature"
                        },
                        new
                        {
                            Id = "057e7c41-48a2-40af-83f7-86495daa66bb",
                            Archived = false,
                            Created = new DateTime(2020, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageLink = "images/child.png",
                            LastUpdated = new DateTime(2020, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Child"
                        },
                        new
                        {
                            Id = "4dc654b1-c887-4000-8e53-309f2aad0e3d",
                            Archived = false,
                            Created = new DateTime(2020, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageLink = "images/historical.png",
                            LastUpdated = new DateTime(2020, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Historical"
                        },
                        new
                        {
                            Id = "9d78cfc4-2299-445c-9c38-d6dd9d081f2b",
                            Archived = false,
                            Created = new DateTime(2020, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageLink = "images/amusement.png",
                            LastUpdated = new DateTime(2020, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Amusement"
                        },
                        new
                        {
                            Id = "3f35dba7-d527-4c70-80cb-68d25ee2b332",
                            Archived = false,
                            Created = new DateTime(2020, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageLink = "images/extreme.png",
                            LastUpdated = new DateTime(2020, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Extreme"
                        });
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Posts.Post", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PostId")
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CatalogRef")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateOfPublication")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(2000)")
                        .HasMaxLength(2000);

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Point>("Location")
                        .HasColumnType("geography");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnName("Title")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK_Posts");

                    b.HasIndex("CatalogRef")
                        .IsUnique()
                        .HasFilter("[CatalogRef] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("Posts","ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Shared.ImageCatalog", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Image_CatalogId")
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Point>("Location")
                        .HasColumnType("geography");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK_Image_Catalogs");

                    b.HasIndex("UserId");

                    b.ToTable("Image_Catalogs","ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Users.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastActivityDate")
                        .HasColumnType("datetime2");

                    b.Property<Point>("Location")
                        .HasColumnType("geography");

                    b.HasKey("Id");

                    b.ToTable("Users","ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Messages.Notification", b =>
                {
                    b.OwnsMany("UrGuide.Data.Entities.Messages.Link", "Links", b1 =>
                        {
                            b1.Property<string>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(450)")
                                .HasDefaultValueSql("NEWID()");

                            b1.Property<string>("MessageId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasColumnType("nvarchar(100)")
                                .HasMaxLength(100);

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("nvarchar(2000)")
                                .HasMaxLength(2000);

                            b1.HasKey("Id");

                            b1.HasIndex("MessageId");

                            b1.ToTable("Message_Links","ug");

                            b1.WithOwner()
                                .HasForeignKey("MessageId");
                        });
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Posts.Post", b =>
                {
                    b.HasOne("UrGuide.Data.Entities.Shared.ImageCatalog", "Catalog")
                        .WithOne("Post")
                        .HasForeignKey("UrGuide.Data.Entities.Posts.Post", "CatalogRef");

                    b.HasOne("UrGuide.Data.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.OwnsMany("UrGuide.Data.Entities.Attributes.GenericAttribute", "Attributes", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(200)")
                                .HasMaxLength(200);

                            b1.Property<string>("PostId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("PostId");

                            b1.ToTable("Post_Attributes","ug");

                            b1.WithOwner()
                                .HasForeignKey("PostId");
                        });

                    b.OwnsOne("UrGuide.Data.Entities.Posts.Bid", "Bid", b1 =>
                        {
                            b1.Property<string>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(450)")
                                .HasDefaultValueSql("NEWID()");

                            b1.Property<string>("FK_Post_Bids_Users")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<DateTime>("LastUpdated")
                                .HasColumnType("datetime2");

                            b1.Property<string>("NewValue")
                                .IsRequired()
                                .HasColumnType("nvarchar(200)")
                                .HasMaxLength(200);

                            b1.Property<string>("OldValue")
                                .HasColumnType("nvarchar(200)")
                                .HasMaxLength(200);

                            b1.Property<string>("PostId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("Id");

                            b1.HasIndex("FK_Post_Bids_Users");

                            b1.HasIndex("PostId")
                                .IsUnique();

                            b1.ToTable("Post_Bids","ug");

                            b1.HasOne("UrGuide.Data.Entities.Users.User", "Author")
                                .WithMany()
                                .HasForeignKey("FK_Post_Bids_Users")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.WithOwner()
                                .HasForeignKey("PostId");
                        });

                    b.OwnsMany("UrGuide.Data.Entities.Posts.BidHistory", "BidHistories", b1 =>
                        {
                            b1.Property<string>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(450)")
                                .HasDefaultValueSql("NEWID()");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("datetime2");

                            b1.Property<string>("FK_Post_Bids_History_Users")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("PostId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(200)")
                                .HasMaxLength(200);

                            b1.HasKey("Id");

                            b1.HasIndex("FK_Post_Bids_History_Users");

                            b1.HasIndex("PostId");

                            b1.ToTable("Post_Bids_History","ug");

                            b1.HasOne("UrGuide.Data.Entities.Users.User", "Author")
                                .WithMany()
                                .HasForeignKey("FK_Post_Bids_History_Users")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.WithOwner()
                                .HasForeignKey("PostId");
                        });

                    b.OwnsMany("UrGuide.Data.Entities.Posts.Itinerary", "Itineraries", b1 =>
                        {
                            b1.Property<string>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(450)")
                                .HasDefaultValueSql("NEWID()");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(500)")
                                .HasMaxLength(500);

                            b1.Property<byte>("Ordinal")
                                .HasColumnType("tinyint");

                            b1.Property<string>("PostId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("nvarchar(100)")
                                .HasMaxLength(100);

                            b1.HasKey("Id");

                            b1.HasIndex("PostId");

                            b1.ToTable("Post_Itineraries","ug");

                            b1.WithOwner()
                                .HasForeignKey("PostId");
                        });

                    b.OwnsMany("UrGuide.Data.Entities.Posts.Reservation", "Reservations", b1 =>
                        {
                            b1.Property<string>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(450)")
                                .HasDefaultValueSql("NEWID()");

                            b1.Property<string>("PostId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Seats")
                                .HasColumnType("int");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("Id");

                            b1.HasIndex("PostId");

                            b1.HasIndex("UserId");

                            b1.ToTable("Seat_Reservations","ug");

                            b1.WithOwner()
                                .HasForeignKey("PostId");

                            b1.HasOne("UrGuide.Data.Entities.Users.User", null)
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });

                    b.OwnsMany("UrGuide.Data.Entities.Posts.UserReaction", "UserReactions", b1 =>
                        {
                            b1.Property<string>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(450)")
                                .HasDefaultValueSql("NEWID()");

                            b1.Property<string>("PostId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("Id");

                            b1.HasIndex("PostId");

                            b1.HasIndex("UserId");

                            b1.ToTable("Post_UserReactions","ug");

                            b1.WithOwner()
                                .HasForeignKey("PostId");

                            b1.HasOne("UrGuide.Data.Entities.Users.User", null)
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });

                    b.OwnsMany("UrGuide.Data.Shared.Feedback", "Feedback", b1 =>
                        {
                            b1.Property<string>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(450)")
                                .HasDefaultValueSql("NEWID()");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("datetime2");

                            b1.Property<string>("FK_Post_Feedback_Users")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<DateTime>("LastUpdated")
                                .HasColumnType("datetime2");

                            b1.Property<string>("PostId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Rating")
                                .HasColumnType("int");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("nvarchar(2000)")
                                .HasMaxLength(2000);

                            b1.HasKey("Id");

                            b1.HasIndex("FK_Post_Feedback_Users");

                            b1.HasIndex("PostId");

                            b1.ToTable("Post_Feedback","ug");

                            b1.HasOne("UrGuide.Data.Entities.Users.User", "Author")
                                .WithMany()
                                .HasForeignKey("FK_Post_Feedback_Users")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.WithOwner()
                                .HasForeignKey("PostId");
                        });
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Shared.ImageCatalog", b =>
                {
                    b.HasOne("UrGuide.Data.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.OwnsMany("UrGuide.Data.Entities.Attributes.GenericAttribute", "Attributes", b1 =>
                        {
                            b1.Property<string>("ImageCatalogId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ImageCatalogId", "Id");

                            b1.ToTable("Image_Catalogs_Attributes");

                            b1.WithOwner()
                                .HasForeignKey("ImageCatalogId");
                        });

                    b.OwnsMany("UrGuide.Data.Entities.Shared.Image", "Images", b1 =>
                        {
                            b1.Property<string>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(450)")
                                .HasDefaultValueSql("NEWID()");

                            b1.Property<string>("ImageUrl")
                                .IsRequired()
                                .HasColumnName("FileBase64")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Image_CatalogId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("MimeType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id")
                                .HasName("PK_Image_Catalog_Files");

                            b1.HasIndex("Image_CatalogId");

                            b1.ToTable("Image_Catalog_Files","ug");

                            b1.WithOwner()
                                .HasForeignKey("Image_CatalogId");

                            b1.OwnsMany("UrGuide.Data.Entities.Attributes.GenericAttribute", "Attributes", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("FileId")
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(200)")
                                        .HasMaxLength(200);

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("FileId");

                                    b2.ToTable("File_Attributes","ug");

                                    b2.WithOwner()
                                        .HasForeignKey("FileId");
                                });
                        });
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Users.User", b =>
                {
                    b.OwnsMany("UrGuide.Data.Entities.Attributes.GenericAttribute", "Attributes", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(200)")
                                .HasMaxLength(200);

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId");

                            b1.ToTable("User_Attributes","ug");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("UrGuide.Data.Entities.Users.Image", "ProfileImage", b1 =>
                        {
                            b1.Property<string>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(450)")
                                .HasDefaultValueSql("NEWID()");

                            b1.Property<string>("ImageUrl")
                                .IsRequired()
                                .HasColumnName("ImageBase64")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("Id")
                                .HasName("PK_User_Images");

                            b1.HasIndex("UserId")
                                .IsUnique();

                            b1.ToTable("User_Images","ug");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsMany("UrGuide.Data.Shared.Feedback", "Feedback", b1 =>
                        {
                            b1.Property<string>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(450)")
                                .HasDefaultValueSql("NEWID()");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("datetime2");

                            b1.Property<string>("FK_User_Feedback_Users")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<DateTime>("LastUpdated")
                                .HasColumnType("datetime2");

                            b1.Property<int>("Rating")
                                .HasColumnType("int");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("nvarchar(2000)")
                                .HasMaxLength(2000);

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("Id")
                                .HasName("PK_User_Feedback");

                            b1.HasIndex("FK_User_Feedback_Users");

                            b1.HasIndex("UserId");

                            b1.ToTable("User_Feedback","ug");

                            b1.HasOne("UrGuide.Data.Entities.Users.User", "Author")
                                .WithMany()
                                .HasForeignKey("FK_User_Feedback_Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
