// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrGuide.Data;

namespace UrGuide.Data.Migrations
{
    [DbContext(typeof(UrGuideContext))]
    [Migration("20200425174913_Initial_01")]
    partial class Initial_01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UrGuide.Data.Entities.Messages.Notification", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MessageId")
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasError")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("Sent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id")
                        .HasName("PK_Messages");

                    b.ToTable("Notifications","ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Posts.Category", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CategoryId")
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("CategoryName")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("PostId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK_Post_Categories");

                    b.HasIndex("PostId");

                    b.ToTable("Post_Categories","ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Posts.Post", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PostId")
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CatalogId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateOfPublication")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(2000)")
                        .HasMaxLength(2000);

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnName("Title")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK_Posts");

                    b.HasIndex("CatalogId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts","ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Shared.ImageCatalog", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Image_CatalogId")
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK_Image_Catalogs");

                    b.HasIndex("UserId");

                    b.ToTable("Image_Catalogs","ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Users.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastActivityDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("Users","ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Messages.Notification", b =>
                {
                    b.OwnsMany("UrGuide.Data.Entities.Messages.Link", "Links", b1 =>
                        {
                            b1.Property<string>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(450)")
                                .HasDefaultValueSql("NEWID()");

                            b1.Property<string>("MessageId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasColumnType("nvarchar(100)")
                                .HasMaxLength(100);

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("nvarchar(2000)")
                                .HasMaxLength(2000);

                            b1.HasKey("Id");

                            b1.HasIndex("MessageId");

                            b1.ToTable("Message_Links","ug");

                            b1.WithOwner()
                                .HasForeignKey("MessageId");
                        });
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Posts.Category", b =>
                {
                    b.HasOne("UrGuide.Data.Entities.Posts.Post", null)
                        .WithMany("Categories")
                        .HasForeignKey("PostId");

                    b.OwnsMany("UrGuide.Data.Entities.Attributes.GenericAttribute", "Attributes", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("CategoryId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(200)")
                                .HasMaxLength(200);

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("CategoryId");

                            b1.ToTable("Post_Categories_Attributes","ug");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId");
                        });

                    b.OwnsOne("UrGuide.Data.Entities.Shared.Image", "Image", b1 =>
                        {
                            b1.Property<string>("CategoryId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Id")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ImageBase64")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ImageCatalogId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("MimeType")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CategoryId");

                            b1.HasIndex("ImageCatalogId");

                            b1.ToTable("Post_Categories");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId");

                            b1.HasOne("UrGuide.Data.Entities.Shared.ImageCatalog", "ImageCatalog")
                                .WithMany()
                                .HasForeignKey("ImageCatalogId");

                            b1.OwnsMany("UrGuide.Data.Entities.Attributes.GenericAttribute", "Attributes", b2 =>
                                {
                                    b2.Property<string>("ImageCategoryId")
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("Name")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Value")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ImageCategoryId", "Id");

                                    b2.ToTable("Post_Categories_Attributes1");

                                    b2.WithOwner()
                                        .HasForeignKey("ImageCategoryId");
                                });
                        });
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Posts.Post", b =>
                {
                    b.HasOne("UrGuide.Data.Entities.Shared.ImageCatalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogId");

                    b.HasOne("UrGuide.Data.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.OwnsMany("UrGuide.Data.Entities.Attributes.GenericAttribute", "Attributes", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(200)")
                                .HasMaxLength(200);

                            b1.Property<string>("PostId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("PostId");

                            b1.ToTable("Post_Attributes","ug");

                            b1.WithOwner()
                                .HasForeignKey("PostId");
                        });
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Shared.ImageCatalog", b =>
                {
                    b.HasOne("UrGuide.Data.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.OwnsMany("UrGuide.Data.Entities.Shared.Image", "Images", b1 =>
                        {
                            b1.Property<string>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(450)")
                                .HasDefaultValueSql("NEWID()");

                            b1.Property<string>("ImageBase64")
                                .IsRequired()
                                .HasColumnName("FileBase64")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ImageCatalogId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Image_CatalogId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("MimeType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id")
                                .HasName("PK_Image_Catalog_Files");

                            b1.HasIndex("ImageCatalogId");

                            b1.HasIndex("Image_CatalogId");

                            b1.ToTable("Image_Catalog_Files","ug");

                            b1.HasOne("UrGuide.Data.Entities.Shared.ImageCatalog", "ImageCatalog")
                                .WithMany()
                                .HasForeignKey("ImageCatalogId");

                            b1.WithOwner()
                                .HasForeignKey("Image_CatalogId");

                            b1.OwnsMany("UrGuide.Data.Entities.Attributes.GenericAttribute", "Attributes", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("FileId")
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(200)")
                                        .HasMaxLength(200);

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("FileId");

                                    b2.ToTable("File_Attributes","ug");

                                    b2.WithOwner()
                                        .HasForeignKey("FileId");
                                });
                        });
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Users.User", b =>
                {
                    b.OwnsMany("UrGuide.Data.Entities.Attributes.GenericAttribute", "Attributes", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(200)")
                                .HasMaxLength(200);

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId");

                            b1.ToTable("User_Attributes","ug");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("UrGuide.Data.Entities.Users.Image", "ProfileImage", b1 =>
                        {
                            b1.Property<string>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(450)")
                                .HasDefaultValueSql("NEWID()");

                            b1.Property<string>("ImageBase64")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("Id")
                                .HasName("PK_User_Images");

                            b1.HasIndex("UserId")
                                .IsUnique();

                            b1.ToTable("User_Images","ug");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
