// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrGuide.Data;

#nullable disable

namespace UrGuide.Data.Migrations
{
    [DbContext(typeof(UrGuideContext))]
    [Migration("20260308000001_AddAvailabilityAndVerification")]
    partial class AddAvailabilityAndVerification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
