// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using UrGuide.Data;

#nullable disable

namespace UrGuide.Data.Migrations
{
    [DbContext(typeof(UrGuideContext))]
    [Migration("20260211081736_OptimizeSetAttributeIndexes")]
    partial class OptimizeSetAttributeIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UrGuide.Data.Entities.Event.AuditEvent", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventCode")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.HasKey("Id");

                    b.ToTable("Audit_Events", "ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Payments.Payment", b =>
                {
                    b.Property<string>("PaymentId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BookingId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("GuidePayout")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Metadata")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<decimal>("PlatformFeeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PaymentId");

                    b.HasIndex("BookingId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CurrencyCode");

                    b.HasIndex("Status");

                    b.HasIndex("StripePaymentIntentId");

                    b.HasIndex("UserId");

                    b.ToTable("payments", "ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Payments.PaymentTransaction", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Metadata")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PaymentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StripeTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PaymentId");

                    b.HasIndex("Type");

                    b.ToTable("payment_transactions", "ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Payments.Payout", b =>
                {
                    b.Property<string>("PayoutId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GuideId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StripeAccountId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StripePayoutId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PayoutId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GuideId");

                    b.HasIndex("RequestedAt");

                    b.HasIndex("Status");

                    b.ToTable("payouts", "ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Payments.PlatformFee", b =>
                {
                    b.Property<string>("FeeId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("MembershipTier")
                        .HasColumnType("int");

                    b.Property<string>("PaymentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.HasKey("FeeId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MembershipTier");

                    b.HasIndex("PaymentId");

                    b.ToTable("platform_fees", "ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Payments.Refund", b =>
                {
                    b.Property<string>("RefundId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PaymentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StripeRefundId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RefundId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PaymentId");

                    b.HasIndex("RequestedAt");

                    b.HasIndex("RequestedBy");

                    b.HasIndex("Status");

                    b.ToTable("refunds", "ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Posts.Category", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CategoryId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CategoryName");

                    b.HasKey("Id")
                        .HasName("PK_Post_Categories");

                    b.ToTable("Post_Categories", "ug");

                    b.HasData(
                        new
                        {
                            Id = "d1442a22-adc5-4eab-a232-6ae1fe1ad4f5",
                            Archived = false,
                            Created = new DateTime(2020, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageLink = "images/sport.png",
                            LastUpdated = new DateTime(2020, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sport"
                        },
                        new
                        {
                            Id = "62cf86ff-755d-46fd-bf8d-ca08ba353451",
                            Archived = false,
                            Created = new DateTime(2020, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageLink = "images/nature.png",
                            LastUpdated = new DateTime(2020, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nature"
                        },
                        new
                        {
                            Id = "057e7c41-48a2-40af-83f7-86495daa66bb",
                            Archived = false,
                            Created = new DateTime(2020, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageLink = "images/child.png",
                            LastUpdated = new DateTime(2020, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Child"
                        },
                        new
                        {
                            Id = "4dc654b1-c887-4000-8e53-309f2aad0e3d",
                            Archived = false,
                            Created = new DateTime(2020, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageLink = "images/historical.png",
                            LastUpdated = new DateTime(2020, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Historical"
                        },
                        new
                        {
                            Id = "9d78cfc4-2299-445c-9c38-d6dd9d081f2b",
                            Archived = false,
                            Created = new DateTime(2020, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageLink = "images/amusement.png",
                            LastUpdated = new DateTime(2020, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Amusement"
                        },
                        new
                        {
                            Id = "3f35dba7-d527-4c70-80cb-68d25ee2b332",
                            Archived = false,
                            Created = new DateTime(2020, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageLink = "images/extreme.png",
                            LastUpdated = new DateTime(2020, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Extreme"
                        });
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Posts.Post", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("PostId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("AllocatedSeats")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("BidCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("BidEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("CatalogRef")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Cost")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateOfPublication")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Dislikes")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeoLocation")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("ItineraryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("LastBid")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<Point>("Location")
                        .HasColumnType("geography");

                    b.Property<int>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<int>("ReservedSeats")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Reviews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Title");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK_Posts");

                    b.HasIndex("CatalogRef")
                        .IsUnique()
                        .HasFilter("[CatalogRef] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("Posts", "ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Regions.Country", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CountryId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DialCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("Name");

                    b.ToTable("countries", "ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Regions.Currency", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CurrencyId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("DecimalDigits")
                        .HasColumnType("int");

                    b.Property<string>("NamePlural")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Rounding")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SymbolNative")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("currencies", "ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Regions.PaymentMethod", b =>
                {
                    b.Property<string>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Secret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Secret2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PaymentMethodId");

                    b.ToTable("payment_methods", "ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Regions.Region", b =>
                {
                    b.Property<string>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CurrencyId")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PaymentMethodId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TimelineId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RegionId");

                    b.HasIndex("CountryId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("TimelineId");

                    b.ToTable("regions", "ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Regions.Timeline", b =>
                {
                    b.Property<string>("TimelineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.HasKey("TimelineId");

                    b.ToTable("region_timelines", "ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Search.SearchAnalytics", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Filters")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("HasResults")
                        .HasColumnType("bit");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("ResultsCount")
                        .HasColumnType("bigint");

                    b.Property<string>("SearchType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("SearchedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("TimeTakenMs")
                        .HasColumnType("bigint");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Query");

                    b.HasIndex("SearchType");

                    b.HasIndex("SearchedAt");

                    b.HasIndex("UserId");

                    b.ToTable("SearchAnalytics", "ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Shared.ImageCatalog", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Image_CatalogId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Point>("Location")
                        .HasColumnType("geography");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK_Image_Catalogs");

                    b.HasIndex("UserId");

                    b.ToTable("Image_Catalogs", "ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Tour.Booking", b =>
                {
                    b.Property<string>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EnablePushNotification")
                        .HasColumnType("bit");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubscriptionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TourId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TourId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("When")
                        .HasColumnType("datetime2");

                    b.HasKey("BookingId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("RegionId");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("TourId");

                    b.HasIndex("TourId1");

                    b.ToTable("tour_booking", "ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Tour.Campain", b =>
                {
                    b.Property<string>("CampainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("ActiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ActiveUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("DescriptionSEO")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Membership")
                        .HasColumnType("int");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TimelineId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CampainId");

                    b.HasIndex("RegionId");

                    b.HasIndex("TimelineId");

                    b.ToTable("campains", "ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Tour.Review", b =>
                {
                    b.Property<string>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("TourId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ReviewId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TourId");

                    b.ToTable("reviews", "ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Tour.Subscription", b =>
                {
                    b.Property<string>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("ActivatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("CanAutoRenew")
                        .HasColumnType("bit");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndsOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Membership")
                        .HasColumnType("int");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TransactionRef")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("RegionId");

                    b.ToTable("subscriptions", "ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Tour.Tour", b =>
                {
                    b.Property<string>("TourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimelineId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TourId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("RegionId");

                    b.HasIndex("TimelineId");

                    b.ToTable("tours", "ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Tour.TourRequest", b =>
                {
                    b.Property<string>("TourRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal>("MaxBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<DateTime>("PreferredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RequesterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TourRequestId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RegionId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("Status");

                    b.ToTable("tour_requests", "ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Users.Author", b =>
                {
                    b.Property<string>("AuthorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BalanceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("SubscriptionId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AuthorId");

                    b.HasIndex("BalanceId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("authors", "ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Users.Balance", b =>
                {
                    b.Property<string>("BalanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<double>("Bonus")
                        .HasColumnType("float");

                    b.Property<double>("Coins")
                        .HasColumnType("float");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BalanceId");

                    b.HasIndex("RegionId");

                    b.ToTable("author_balance", "ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Users.DataExportRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DownloadToken")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("DownloadToken")
                        .IsUnique()
                        .HasFilter("[DownloadToken] IS NOT NULL");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("DataExportRequests", "ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Users.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UserId");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("N/A");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("N/A");

                    b.Property<DateTime>("LastActivityDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("N/A");

                    b.Property<Point>("Location")
                        .HasColumnType("geography");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Users", "ug");

                    b.HasData(
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000000",
                            CreatedAt = new DateTime(2020, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            LastActivityDate = new DateTime(2020, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Webhooks.WebhookDelivery", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Event")
                        .HasColumnType("int");

                    b.Property<int>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseBody")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("int");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("WebhookSubscriptionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("NextRetryAt");

                    b.HasIndex("Status");

                    b.HasIndex("WebhookSubscriptionId");

                    b.ToTable("webhook_deliveries", "ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Webhooks.WebhookSubscription", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Events")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailureCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SuccessCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsActive");

                    b.HasIndex("UserId");

                    b.ToTable("webhook_subscriptions", "ug");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Payments.Payment", b =>
                {
                    b.HasOne("UrGuide.Data.Entities.Tour.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UrGuide.Data.Entities.Regions.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UrGuide.Data.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Currency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Payments.PaymentTransaction", b =>
                {
                    b.HasOne("UrGuide.Data.Entities.Payments.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Payments.Payout", b =>
                {
                    b.HasOne("UrGuide.Data.Entities.Users.Author", "Guide")
                        .WithMany()
                        .HasForeignKey("GuideId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Guide");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Payments.PlatformFee", b =>
                {
                    b.HasOne("UrGuide.Data.Entities.Payments.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Payments.Refund", b =>
                {
                    b.HasOne("UrGuide.Data.Entities.Payments.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UrGuide.Data.Entities.Users.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Posts.Post", b =>
                {
                    b.HasOne("UrGuide.Data.Entities.Shared.ImageCatalog", "Catalog")
                        .WithOne("Post")
                        .HasForeignKey("UrGuide.Data.Entities.Posts.Post", "CatalogRef");

                    b.HasOne("UrGuide.Data.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.OwnsOne("UrGuide.Data.Entities.Posts.Bid", "Bid", b1 =>
                        {
                            b1.Property<string>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(450)")
                                .HasDefaultValueSql("NEWID()");

                            b1.Property<string>("FK_Post_Bids_Users")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<DateTime>("LastUpdated")
                                .HasColumnType("datetime2");

                            b1.Property<string>("NewValue")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("OldValue")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("PostId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("Id");

                            b1.HasIndex("FK_Post_Bids_Users");

                            b1.HasIndex("PostId")
                                .IsUnique();

                            b1.ToTable("Post_Bids", "ug");

                            b1.HasOne("UrGuide.Data.Entities.Users.User", "Author")
                                .WithMany()
                                .HasForeignKey("FK_Post_Bids_Users")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.WithOwner()
                                .HasForeignKey("PostId");

                            b1.Navigation("Author");
                        });

                    b.OwnsMany("UrGuide.Data.Entities.Posts.BidHistory", "BidHistories", b1 =>
                        {
                            b1.Property<string>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(450)")
                                .HasDefaultValueSql("NEWID()");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("datetime2");

                            b1.Property<string>("FK_Post_Bids_History_Users")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("PostId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.HasKey("Id");

                            b1.HasIndex("FK_Post_Bids_History_Users");

                            b1.HasIndex("PostId");

                            b1.ToTable("Post_Bids_History", "ug");

                            b1.HasOne("UrGuide.Data.Entities.Users.User", "Author")
                                .WithMany()
                                .HasForeignKey("FK_Post_Bids_History_Users")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.WithOwner()
                                .HasForeignKey("PostId");

                            b1.Navigation("Author");
                        });

                    b.OwnsMany("UrGuide.Data.Entities.Posts.Itinerary", "Itineraries", b1 =>
                        {
                            b1.Property<string>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(450)")
                                .HasDefaultValueSql("NEWID()");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<byte>("Ordinal")
                                .HasColumnType("tinyint");

                            b1.Property<string>("PostId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("Id");

                            b1.HasIndex("PostId");

                            b1.ToTable("Post_Itineraries", "ug");

                            b1.WithOwner()
                                .HasForeignKey("PostId");
                        });

                    b.OwnsMany("UrGuide.Data.Shared.Feedback", "Feedback", b1 =>
                        {
                            b1.Property<string>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(450)")
                                .HasDefaultValueSql("NEWID()");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("datetime2");

                            b1.Property<string>("FK_Post_Feedback_Users")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<DateTime>("LastUpdated")
                                .HasColumnType("datetime2");

                            b1.Property<string>("PostId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Rating")
                                .HasColumnType("int");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)");

                            b1.HasKey("Id");

                            b1.HasIndex("FK_Post_Feedback_Users");

                            b1.HasIndex("PostId");

                            b1.ToTable("Post_Feedback", "ug");

                            b1.HasOne("UrGuide.Data.Entities.Users.User", "Author")
                                .WithMany()
                                .HasForeignKey("FK_Post_Feedback_Users")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.WithOwner()
                                .HasForeignKey("PostId");

                            b1.Navigation("Author");
                        });

                    b.OwnsMany("UrGuide.Data.Entities.Posts.Reservation", "Reservations", b1 =>
                        {
                            b1.Property<string>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(450)")
                                .HasDefaultValueSql("NEWID()");

                            b1.Property<string>("PostId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Seats")
                                .HasColumnType("int");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("Id");

                            b1.HasIndex("PostId");

                            b1.HasIndex("UserId");

                            b1.ToTable("Seat_Reservations", "ug");

                            b1.WithOwner()
                                .HasForeignKey("PostId");

                            b1.HasOne("UrGuide.Data.Entities.Users.User", null)
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });

                    b.OwnsMany("UrGuide.Data.Entities.Posts.UserReaction", "UserReactions", b1 =>
                        {
                            b1.Property<string>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(450)")
                                .HasDefaultValueSql("NEWID()");

                            b1.Property<string>("PostId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("Id");

                            b1.HasIndex("PostId");

                            b1.HasIndex("UserId");

                            b1.ToTable("Post_UserReactions", "ug");

                            b1.WithOwner()
                                .HasForeignKey("PostId");

                            b1.HasOne("UrGuide.Data.Entities.Users.User", null)
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });

                    b.Navigation("Bid");

                    b.Navigation("BidHistories");

                    b.Navigation("Catalog");

                    b.Navigation("Feedback");

                    b.Navigation("Itineraries");

                    b.Navigation("Reservations");

                    b.Navigation("User");

                    b.Navigation("UserReactions");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Regions.Region", b =>
                {
                    b.HasOne("UrGuide.Data.Entities.Regions.Country", "Country")
                        .WithMany("Regions")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrGuide.Data.Entities.Regions.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId");

                    b.HasOne("UrGuide.Data.Entities.Regions.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId");

                    b.HasOne("UrGuide.Data.Entities.Regions.Timeline", "Timeline")
                        .WithMany()
                        .HasForeignKey("TimelineId");

                    b.OwnsOne("UrGuide.Data.Entities.Regions.RegionFlags", "Flags", b1 =>
                        {
                            b1.Property<string>("RegionId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<bool>("Active")
                                .HasColumnType("bit");

                            b1.Property<bool>("CanMakePayments")
                                .HasColumnType("bit");

                            b1.Property<bool>("CanMakeReservations")
                                .HasColumnType("bit");

                            b1.Property<bool>("CanRaiseTourRequests")
                                .HasColumnType("bit");

                            b1.Property<bool>("CanRegisterUsers")
                                .HasColumnType("bit");

                            b1.HasKey("RegionId");

                            b1.ToTable("regions", "ug");

                            b1.WithOwner()
                                .HasForeignKey("RegionId");
                        });

                    b.OwnsOne("UrGuide.Data.Entities.Regions.RegionStats", "Stats", b1 =>
                        {
                            b1.Property<string>("RegionId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("RegisteredGuides")
                                .HasColumnType("int");

                            b1.Property<int>("RegisteredUsers")
                                .HasColumnType("int");

                            b1.Property<int>("ToursOverallCount")
                                .HasColumnType("int");

                            b1.HasKey("RegionId");

                            b1.ToTable("regions", "ug");

                            b1.WithOwner()
                                .HasForeignKey("RegionId");
                        });

                    b.Navigation("Country");

                    b.Navigation("Currency");

                    b.Navigation("Flags");

                    b.Navigation("PaymentMethod");

                    b.Navigation("Stats");

                    b.Navigation("Timeline");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Shared.ImageCatalog", b =>
                {
                    b.HasOne("UrGuide.Data.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.OwnsMany("UrGuide.Core.Attributes.GenericAttribute", "Attributes", b1 =>
                        {
                            b1.Property<string>("ImageCatalogId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ImageCatalogId", "Id");

                            b1.ToTable("Image_Catalogs_Attributes", "ug");

                            b1.WithOwner()
                                .HasForeignKey("ImageCatalogId");
                        });

                    b.OwnsMany("UrGuide.Data.Entities.Shared.Image", "Images", b1 =>
                        {
                            b1.Property<string>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(450)")
                                .HasDefaultValueSql("NEWID()");

                            b1.Property<string>("ImageUrl")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("FileBase64");

                            b1.Property<string>("Image_CatalogId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("MimeType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id")
                                .HasName("PK_Image_Catalog_Files");

                            b1.HasIndex("Image_CatalogId");

                            b1.ToTable("Image_Catalog_Files", "ug");

                            b1.WithOwner()
                                .HasForeignKey("Image_CatalogId");

                            b1.OwnsMany("UrGuide.Core.Attributes.GenericAttribute", "Attributes", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("FileId")
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("FileId");

                                    b2.HasIndex("Name")
                                        .HasDatabaseName("IX_File_Attributes_Name");

                                    b2.ToTable("File_Attributes", "ug");

                                    b2.WithOwner()
                                        .HasForeignKey("FileId");
                                });

                            b1.Navigation("Attributes");
                        });

                    b.Navigation("Attributes");

                    b.Navigation("Images");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Tour.Booking", b =>
                {
                    b.HasOne("UrGuide.Data.Entities.Users.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrGuide.Data.Entities.Regions.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrGuide.Data.Entities.Tour.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId");

                    b.HasOne("UrGuide.Data.Entities.Tour.Tour", "Tour")
                        .WithMany()
                        .HasForeignKey("TourId");

                    b.HasOne("UrGuide.Data.Entities.Tour.Tour", null)
                        .WithMany("Bookings")
                        .HasForeignKey("TourId1");

                    b.Navigation("Author");

                    b.Navigation("Region");

                    b.Navigation("Subscription");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Tour.Campain", b =>
                {
                    b.HasOne("UrGuide.Data.Entities.Regions.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrGuide.Data.Entities.Regions.Timeline", null)
                        .WithMany("Campains")
                        .HasForeignKey("TimelineId");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Tour.Review", b =>
                {
                    b.HasOne("UrGuide.Data.Entities.Users.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrGuide.Data.Entities.Tour.Tour", null)
                        .WithMany("Reviews")
                        .HasForeignKey("TourId");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Tour.Subscription", b =>
                {
                    b.HasOne("UrGuide.Data.Entities.Users.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrGuide.Data.Entities.Regions.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("UrGuide.Data.Entities.Tour.CreditCardInfo", "CreditCard", b1 =>
                        {
                            b1.Property<string>("SubscriptionId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("CardHolderName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("CardNumber")
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)");

                            b1.Property<byte>("ExpiryMonth")
                                .HasColumnType("tinyint");

                            b1.Property<short>("ExpiryYear")
                                .HasColumnType("smallint");

                            b1.HasKey("SubscriptionId");

                            b1.ToTable("subscriptions", "ug");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionId");
                        });

                    b.Navigation("Author");

                    b.Navigation("CreditCard");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Tour.Tour", b =>
                {
                    b.HasOne("UrGuide.Data.Entities.Users.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrGuide.Data.Entities.Regions.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrGuide.Data.Entities.Regions.Timeline", null)
                        .WithMany("Items")
                        .HasForeignKey("TimelineId");

                    b.OwnsMany("UrGuide.Data.Entities.Tour.MapPin", "MapPins", b1 =>
                        {
                            b1.Property<string>("MapPinId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(450)")
                                .HasDefaultValueSql("NEWID()");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)");

                            b1.Property<string>("ImageUrl")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("float");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("TourId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("MapPinId");

                            b1.HasIndex("TourId");

                            b1.ToTable("tours_map_pins", "ug");

                            b1.WithOwner()
                                .HasForeignKey("TourId");
                        });

                    b.OwnsMany("UrGuide.Data.Entities.Tour.Reaction", "Reactions", b1 =>
                        {
                            b1.Property<string>("ReactionId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(450)")
                                .HasDefaultValueSql("NEWID()");

                            b1.Property<string>("AuthorId")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TourId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("ReactionId");

                            b1.HasIndex("TourId");

                            b1.ToTable("tour_reactions", "ug");

                            b1.WithOwner()
                                .HasForeignKey("TourId");
                        });

                    b.OwnsOne("UrGuide.Data.Entities.Tour.Schedule", "Schedule", b1 =>
                        {
                            b1.Property<string>("TourId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<DateTime>("ActiveFrom")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ActiveUntil")
                                .HasColumnType("datetime2");

                            b1.Property<TimeSpan>("EndTime")
                                .HasColumnType("time");

                            b1.Property<DateTime?>("NextRun")
                                .HasColumnType("datetime2");

                            b1.Property<TimeSpan>("StartTime")
                                .HasColumnType("time");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.HasKey("TourId");

                            b1.ToTable("tours", "ug");

                            b1.WithOwner()
                                .HasForeignKey("TourId");
                        });

                    b.OwnsOne("UrGuide.Data.Entities.Tour.TourStats", "Stats", b1 =>
                        {
                            b1.Property<string>("TourId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Likes")
                                .HasColumnType("int");

                            b1.Property<int>("MapItsCount")
                                .HasColumnType("int");

                            b1.Property<int>("Rating")
                                .HasColumnType("int");

                            b1.Property<int>("ReactionsCount")
                                .HasColumnType("int");

                            b1.Property<int>("ReservedSeats")
                                .HasColumnType("int");

                            b1.Property<int>("ReviewsCount")
                                .HasColumnType("int");

                            b1.Property<int>("SharedCount")
                                .HasColumnType("int");

                            b1.Property<int>("Views")
                                .HasColumnType("int");

                            b1.HasKey("TourId");

                            b1.ToTable("tours", "ug");

                            b1.WithOwner()
                                .HasForeignKey("TourId");
                        });

                    b.Navigation("Author");

                    b.Navigation("MapPins");

                    b.Navigation("Reactions");

                    b.Navigation("Region");

                    b.Navigation("Schedule");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Tour.TourRequest", b =>
                {
                    b.HasOne("UrGuide.Data.Entities.Regions.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrGuide.Data.Entities.Users.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Users.Author", b =>
                {
                    b.HasOne("UrGuide.Data.Entities.Users.Balance", "Balance")
                        .WithMany()
                        .HasForeignKey("BalanceId");

                    b.HasOne("UrGuide.Data.Entities.Tour.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId");

                    b.OwnsOne("UrGuide.Data.Entities.Users.AuthorActivity", "Activity", b1 =>
                        {
                            b1.Property<string>("AuthorId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<DateTime>("LastActive")
                                .HasColumnType("datetime2");

                            b1.HasKey("AuthorId");

                            b1.ToTable("authors", "ug");

                            b1.WithOwner()
                                .HasForeignKey("AuthorId");
                        });

                    b.OwnsOne("UrGuide.Data.Entities.Users.AuthorProfile", "ProfileInfo", b1 =>
                        {
                            b1.Property<string>("AuthorId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("ImageUrl")
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)");

                            b1.Property<string>("PhoneNumber")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("datetime2");

                            b1.HasKey("AuthorId");

                            b1.ToTable("authors", "ug");

                            b1.WithOwner()
                                .HasForeignKey("AuthorId");
                        });

                    b.Navigation("Activity");

                    b.Navigation("Balance");

                    b.Navigation("ProfileInfo");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Users.Balance", b =>
                {
                    b.HasOne("UrGuide.Data.Entities.Regions.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Users.DataExportRequest", b =>
                {
                    b.HasOne("UrGuide.Data.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Users.User", b =>
                {
                    b.OwnsOne("UrGuide.Data.Entities.Users.Image", "ProfileImage", b1 =>
                        {
                            b1.Property<string>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(450)")
                                .HasDefaultValueSql("NEWID()");

                            b1.Property<string>("ImageUrl")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ImageBase64");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("Id")
                                .HasName("PK_User_Images");

                            b1.HasIndex("UserId")
                                .IsUnique();

                            b1.ToTable("User_Images", "ug");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsMany("UrGuide.Data.Entities.Users.Notification", "Notifications", b1 =>
                        {
                            b1.Property<string>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(450)")
                                .HasDefaultValueSql("NEWID()");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("datetime2");

                            b1.Property<string>("FK_User_Notification_Users")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<bool>("IsSystem")
                                .HasColumnType("bit");

                            b1.Property<bool>("Read")
                                .HasColumnType("bit");

                            b1.Property<string>("ReferenceLink")
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("Id");

                            b1.HasIndex("FK_User_Notification_Users");

                            b1.HasIndex("UserId");

                            b1.ToTable("User_Notifications", "ug");

                            b1.HasOne("UrGuide.Data.Entities.Users.User", "Sender")
                                .WithMany()
                                .HasForeignKey("FK_User_Notification_Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.Navigation("Sender");
                        });

                    b.OwnsMany("UrGuide.Core.Attributes.GenericAttribute", "Attributes", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("Name")
                                .HasDatabaseName("IX_User_Attributes_Name");

                            b1.HasIndex("UserId");

                            b1.ToTable("User_Attributes", "ug");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsMany("UrGuide.Data.Shared.Feedback", "Feedback", b1 =>
                        {
                            b1.Property<string>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(450)")
                                .HasDefaultValueSql("NEWID()");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("datetime2");

                            b1.Property<string>("FK_User_Feedback_Users")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<DateTime>("LastUpdated")
                                .HasColumnType("datetime2");

                            b1.Property<int>("Rating")
                                .HasColumnType("int");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("Id")
                                .HasName("PK_User_Feedback");

                            b1.HasIndex("FK_User_Feedback_Users");

                            b1.HasIndex("UserId");

                            b1.ToTable("User_Feedback", "ug");

                            b1.HasOne("UrGuide.Data.Entities.Users.User", "Author")
                                .WithMany()
                                .HasForeignKey("FK_User_Feedback_Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.Navigation("Author");
                        });

                    b.Navigation("Attributes");

                    b.Navigation("Feedback");

                    b.Navigation("Notifications");

                    b.Navigation("ProfileImage");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Webhooks.WebhookDelivery", b =>
                {
                    b.HasOne("UrGuide.Data.Entities.Webhooks.WebhookSubscription", "WebhookSubscription")
                        .WithMany()
                        .HasForeignKey("WebhookSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebhookSubscription");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Webhooks.WebhookSubscription", b =>
                {
                    b.HasOne("UrGuide.Data.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Regions.Country", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Regions.Timeline", b =>
                {
                    b.Navigation("Campains");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Shared.ImageCatalog", b =>
                {
                    b.Navigation("Post");
                });

            modelBuilder.Entity("UrGuide.Data.Entities.Tour.Tour", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
