// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using UrGuide.Data;

#nullable disable

namespace UrGuide.Data.Migrations
{
    [DbContext(typeof(UrGuideContext))]
    [Migration("20260308000002_AddGuideResponseToFeedback")]
    partial class AddGuideResponseToFeedback
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
