<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>UrGuide.MAUI</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- Core packages for .NET 8.0 class library -->
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="IdentityModel" Version="6.2.0" />
    <PackageReference Include="IdentityModel.OidcClient" Version="5.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Include="Akavache" Version="9.1.1" />
    <PackageReference Include="Akavache.Sqlite3" Version="9.1.1" />
    <PackageReference Include="System.Reactive" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UrGuide.Model\UrGuide.Model.csproj" />
  </ItemGroup>

  <!-- Fonts will be migrated as embedded resources for now -->
  <ItemGroup>
    <EmbeddedResource Include="Resources\Fonts\Font Awesome 5 Free-Regular-400.otf" />
    <EmbeddedResource Include="Resources\Fonts\Font Awesome 5 Free-Solid-900.otf" />
    <EmbeddedResource Include="Resources\Fonts\OpenSans-Bold.ttf" />
    <EmbeddedResource Include="Resources\Fonts\OpenSans-BoldItalic.ttf" />
    <EmbeddedResource Include="Resources\Fonts\OpenSans-ExtraBold.ttf" />
    <EmbeddedResource Include="Resources\Fonts\OpenSans-Italic.ttf" />
    <EmbeddedResource Include="Resources\Fonts\OpenSans-Regular.ttf" />
    <EmbeddedResource Include="Resources\Fonts\OpenSansBold.ttf" />
  </ItemGroup>

</Project>