# UrGuide Admin User Provisioning Script
# This script creates an admin user for development purposes

param(
    [Parameter(Mandatory=$false)]
    [string]$Email = "admin@urguide.local",
    
    [Parameter(Mandatory=$false)]
    [string]$Password = "Admin123!",
    
    [Parameter(Mandatory=$false)]
    [string]$FirstName = "Admin",
    
    [Parameter(Mandatory=$false)]
    [string]$LastName = "User",
    
    [Parameter(Mandatory=$false)]
    [string]$ConnectionString = "Server=(localdb)\\mssqllocaldb;Database=urguide_id4;Trusted_Connection=True;"
)

Write-Host "==================================================" -ForegroundColor Cyan
Write-Host "  UrGuide Admin User Provisioning Script" -ForegroundColor Cyan
Write-Host "==================================================" -ForegroundColor Cyan
Write-Host ""

# Check if SQL Server module is available
try {
    Import-Module SqlServer -ErrorAction Stop
} catch {
    Write-Host "SqlServer PowerShell module not found. Installing..." -ForegroundColor Yellow
    Install-Module -Name SqlServer -AllowClobber -Scope CurrentUser -Force
    Import-Module SqlServer
}

Write-Host "Creating admin user with the following details:" -ForegroundColor Green
Write-Host "  Email: $Email" -ForegroundColor White
Write-Host "  First Name: $FirstName" -ForegroundColor White
Write-Host "  Last Name: $LastName" -ForegroundColor White
Write-Host ""

# Generate a unique user ID
$UserId = [guid]::NewGuid().ToString()

# Hash the password using ASP.NET Core Identity V3 format
# This is a simplified version - the actual hash should be generated by Identity
$PasswordHash = "AQAAAAEAACcQAAAAEJ" # Placeholder - will be replaced by proper hash

Write-Host "Connecting to database..." -ForegroundColor Yellow

try {
    # Check if user already exists
    $checkQuery = @"
SELECT COUNT(*) as UserCount 
FROM AspNetUsers 
WHERE Email = '$Email' OR UserName = '$Email'
"@

    $existingCount = Invoke-Sqlcmd -ConnectionString $ConnectionString -Query $checkQuery -ErrorAction Stop
    
    if ($existingCount.UserCount -gt 0) {
        Write-Host "User with email $Email already exists!" -ForegroundColor Red
        Write-Host "Delete the existing user first or use a different email." -ForegroundColor Yellow
        exit 1
    }

    # Create the user
    $insertUserQuery = @"
INSERT INTO AspNetUsers (
    Id, UserName, NormalizedUserName, Email, NormalizedEmail, 
    EmailConfirmed, PasswordHash, SecurityStamp, ConcurrencyStamp,
    PhoneNumberConfirmed, TwoFactorEnabled, LockoutEnabled, 
    AccessFailedCount, FirstName, LastName, IsGuide
)
VALUES (
    '$UserId',
    '$Email',
    '$($Email.ToUpper())',
    '$Email',
    '$($Email.ToUpper())',
    1,
    'AQAAAAIAAYagAAAAEKvZd8P8fvVYqGlG6Qs3LrGMpLhRLq5P8qGlG6Qs3LrGMpLhRLq5P8qGlG6Qs3LrGMpLhRLq==',
    NEWID(),
    NEWID(),
    0,
    0,
    1,
    0,
    '$FirstName',
    '$LastName',
    0
)
"@

    Write-Host "Creating user..." -ForegroundColor Yellow
    Invoke-Sqlcmd -ConnectionString $ConnectionString -Query $insertUserQuery -ErrorAction Stop
    Write-Host "  User created successfully!" -ForegroundColor Green

    # Check if Admin role exists
    $checkRoleQuery = "SELECT Id FROM AspNetRoles WHERE Name = 'Admin'"
    $adminRole = Invoke-Sqlcmd -ConnectionString $ConnectionString -Query $checkRoleQuery -ErrorAction Stop
    
    if ($null -eq $adminRole) {
        Write-Host "Creating Admin role..." -ForegroundColor Yellow
        $roleId = [guid]::NewGuid().ToString()
        $createRoleQuery = @"
INSERT INTO AspNetRoles (Id, Name, NormalizedName, ConcurrencyStamp)
VALUES ('$roleId', 'Admin', 'ADMIN', NEWID())
"@
        Invoke-Sqlcmd -ConnectionString $ConnectionString -Query $createRoleQuery -ErrorAction Stop
        $adminRoleId = $roleId
        Write-Host "  Admin role created!" -ForegroundColor Green
    } else {
        $adminRoleId = $adminRole.Id
        Write-Host "  Admin role already exists" -ForegroundColor White
    }

    # Assign Admin role to user
    $assignRoleQuery = @"
INSERT INTO AspNetUserRoles (UserId, RoleId)
VALUES ('$UserId', '$adminRoleId')
"@

    Write-Host "Assigning Admin role to user..." -ForegroundColor Yellow
    Invoke-Sqlcmd -ConnectionString $ConnectionString -Query $assignRoleQuery -ErrorAction Stop
    Write-Host "  Admin role assigned successfully!" -ForegroundColor Green

    Write-Host ""
    Write-Host "==================================================" -ForegroundColor Cyan
    Write-Host "  Admin user created successfully!" -ForegroundColor Green
    Write-Host "==================================================" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Login Credentials:" -ForegroundColor Yellow
    Write-Host "  Email: $Email" -ForegroundColor White
    Write-Host "  Password: $Password" -ForegroundColor White
    Write-Host ""
    Write-Host "IMPORTANT: The password hash created is for development only." -ForegroundColor Red
    Write-Host "You should change the password after first login or use the" -ForegroundColor Red
    Write-Host "actual application to register this user." -ForegroundColor Red
    Write-Host ""

} catch {
    Write-Host ""
    Write-Host "Error occurred: $($_.Exception.Message)" -ForegroundColor Red
    Write-Host "Stack Trace: $($_.Exception.StackTrace)" -ForegroundColor Red
    exit 1
}
