<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Font Awesome 5 Free-Regular-400.otf" />
    <None Remove="Resources\Font Awesome 5 Free-Solid-900.otf" />
    <None Remove="Resources\OpenSans-Bold.ttf" />
    <None Remove="Resources\OpenSans-BoldItalic.ttf" />
    <None Remove="Resources\OpenSans-ExtraBold.ttf" />
    <None Remove="Resources\OpenSans-ExtraBoldItalic.ttf" />
    <None Remove="Resources\OpenSans-Italic.ttf" />
    <None Remove="Resources\OpenSans-Light.ttf" />
    <None Remove="Resources\OpenSans-LightItalic.ttf" />
    <None Remove="Resources\OpenSans-Regular.ttf" />
    <None Remove="Resources\OpenSans-SemiBold.ttf" />
    <None Remove="Resources\OpenSans-SemiBoldItalic.ttf" />
    <None Remove="Resources\OpenSansBold.ttf" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Font Awesome 5 Free-Regular-400.otf" />
    <EmbeddedResource Include="Resources\Font Awesome 5 Free-Solid-900.otf" />
    <EmbeddedResource Include="Resources\OpenSans-Bold.ttf" />
    <EmbeddedResource Include="Resources\OpenSans-BoldItalic.ttf" />
    <EmbeddedResource Include="Resources\OpenSans-ExtraBold.ttf" />
    <EmbeddedResource Include="Resources\OpenSans-ExtraBoldItalic.ttf" />
    <EmbeddedResource Include="Resources\OpenSans-Italic.ttf" />
    <EmbeddedResource Include="Resources\OpenSans-Light.ttf" />
    <EmbeddedResource Include="Resources\OpenSans-LightItalic.ttf" />
    <EmbeddedResource Include="Resources\OpenSans-Regular.ttf" />
    <EmbeddedResource Include="Resources\OpenSans-SemiBold.ttf" />
    <EmbeddedResource Include="Resources\OpenSans-SemiBoldItalic.ttf" />
    <EmbeddedResource Include="Resources\OpenSansBold.ttf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="akavache" Version="7.1.1" />
    <PackageReference Include="akavache.sqlite3" Version="7.1.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="IdentityModel" Version="4.4.0" />
    <PackageReference Include="IdentityModel.OidcClient" Version="3.1.2" />
    <PackageReference Include="Microsoft.AppCenter.Analytics" Version="3.4.3" />
    <PackageReference Include="Microsoft.AppCenter.Crashes" Version="3.4.3" />
    <PackageReference Include="Microsoft.AppCenter.Distribute" Version="3.4.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="5.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="ReactiveUI" Version="11.5.35" />
    <PackageReference Include="Refractored.MvvmHelpers" Version="1.6.2" />
    <PackageReference Include="Sharpnado.Presentation.Forms" Version="1.7.1" />
    <PackageReference Include="Sharpnado.Shadows" Version="1.2.0" />
    <PackageReference Include="Xamarin.FFImageLoading.Forms" Version="2.4.11.982" />
    <PackageReference Include="Xamarin.Forms" Version="4.8.0.1687" />  
    <PackageReference Include="Xamarin.Essentials" Version="1.6.0-pre2" />  
    <PackageReference Include="Xamarin.Forms.PancakeView" Version="2.3.0.759" />  
    <PackageReference Include="Xamarin.Forms.Visual.Material" Version="4.8.0.1687" />  
    <PackageReference Include="Xamarin.Plugin.SharedTransitions" Version="2.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\UrGuide.Model\UrGuide.Model.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\PostPage.xaml.cs">
      <DependentUpon>PostPage.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Views\Controls\Avatar.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\CreatePost.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Dialog\BidDialog.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Dialog\ChangePassword.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Dialog\CreateGallery.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Dialog\CreateItinerary.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Dialog\EditProfile.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Dialog\YesNoConfirmation.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Discover.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Favorite.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\MainPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Notifications.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\PostPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\PostDetailPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Profile.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Controls\Rating.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ProfilePage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Templates\FavoriteItemTemplate.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Templates\PostDetailTemplate.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Templates\PostListItemTemplate.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Templates\Profile\GalleryTemplate.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Templates\Profile\PostsTemplate.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Templates\Profile\ReviewsTemplate.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
  </ItemGroup>
</Project>