import React, { createContext } from "react";

const GuideContext = createContext({
  email: null,
  password: null,
  confirmPassword: null,
  profilePic: null,
  firstName: null,
  lastName: null,
  gender: null,
  birthday: null,
  country: null,
  city: null,
  phone: null,
  address: null,
  description: null,
  picture1: null,
  picture2: null,
  picture3: null,
  picture4: null,
  picture5: null,
  picture6: null,
  emailError: false,
  passwordError: false,
  passwordsDontMatch: false,
  profilePicError: false,
  fnameError: false,
  lnameError: false,
  phoneError: false,
  cityError: false,
  addressError: false,
  genderError: false,
  descriptionError: false,
  pic1Error: false,
  pic2Error: false,
  pic3Error: false,
  pic4Error: false,
  pic5Error: false,
  pic6Error: false,
  isChecked: true,
  step: 0,
  newly: true
});

export default GuideContext;
