<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <LangVersion>14.0</LangVersion>
    <UserSecretsId>d216c234-b1d4-4e9e-be44-0c9a46cdacde</UserSecretsId>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.1" />
    <PackageReference Include="AspNet.Security.OAuth.Apple" Version="10.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.Elasticsearch" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.Rabbitmq" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="9.0.0" />
    <PackageReference Include="AspNetCoreRateLimit" Version="5.0.0" />
    <PackageReference Include="Duende.IdentityModel" Version="8.0.0" />
    <PackageReference Include="Fido2.AspNet" Version="3.0.1" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="MassTransit" Version="8.3.4" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.4" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="10.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.MicrosoftAccount" Version="10.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" Version="10.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.2" />
    <PackageReference Include="Microsoft.Azure.SignalR" Version="1.32.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.OpenApi" Version="2.4.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
    <PackageReference Include="NEST" Version="7.17.5" />
    <PackageReference Include="NLog.Targets.Seq" Version="4.0.2" />
    <PackageReference Include="QRCoder" Version="1.4.3" />
    <PackageReference Include="SendGrid" Version="9.29.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.2" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="6.1.1" />
    <PackageReference Include="NLog" Version="6.1.0" />
    <PackageReference Include="Duende.IdentityServer" Version="7.4.5" />
    <PackageReference Include="Duende.IdentityServer.AspNetIdentity" Version="7.4.5" />
    <PackageReference Include="Duende.IdentityServer.EntityFramework" Version="7.4.5" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.2" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\UrGuide.Services\UrGuide.Services.csproj" />
    <ProjectReference Include="..\UrGuide.Shared\UrGuide.Shared.csproj" />
    <ProjectReference Include="..\UrGuide.ServiceDefaults\UrGuide.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
